name: {{PROJECT}}

on:
  pull_request:
    branches:
      - main
      - feat**
    types: [ closed ]
    paths:
      - "projects/{{PROJECT}}/**"
      - "./github/workflows/{{PROJECT}}.yaml"
  delete:
    branches:
      - 'feat**'

jobs: