name: {{PROJECT}}

on:
  pull_request:
    branches:
      - main
    types: [ closed ]
  push:
    branches:
      - 'feat**'
    paths:
      - "projects/{{PROJECT}}/**"
      - "./github/workflows/{{PROJECT}}.yaml"

jobs: