name: "{{PROJECT}}"

on:
  push:
    branches:
      - 'develop'
    paths:
      - "projects/{{PROJECT}}/**"
      - "./github/workflows/{{PROJECT}}.yaml"

jobs:
  {{PROJECT}}-product:
    # reusable workflows MUST be in .github/workflows
    uses: ./.github/workflows/reusable-cdk-cicd-workflow.yaml
    permissions:
      id-token: write
      contents: read
    with:
      # 0으로 시작하는 AccountID 때문에 문자열로 명시
      aws_account_id: "{{TAGET_ACCOUNT}}"
      stage: "prod"
      app_name: "{{PROJECT}}"