name: github-oidc-provider

on:
  pull_request:
    branches:
      - main
    types: [ closed ]
  push:
    branches:
      - 'feat**'
    paths:
      - "projects/github-oidc-provider/**"
      - "./github/workflows/github-oidc-provider.yaml"

jobs:
  github-oidc-provider:
    # reusable workflows MUST be in .github/workflows
    uses: ./.github/workflows/reusable-cdk-cicd-workflow.yaml
    permissions:
      id-token: write
      contents: read
    with:
      # 0으로 시작하는 AccountID 때문에 문자열로 명시
      aws_account_id: '037729278610'
      stage: prod
      app_name: github-oidc-provider
      pipeline_execution_role: github-deploy-role
