name: network

on:
  push:
    branches:
      - 'develop'
    paths:
      - "projects/network/**"
      - "./github/workflows/network.yaml"

jobs:
  network-037729278610:
    # reusable workflows MUST be in .github/workflows
    uses: ./.github/workflows/reusable-cdk-cicd-workflow.yaml
    permissions:
      id-token: write
      contents: read
    with:
      # 0으로 시작하는 AccountID 때문에 문자열로 명시
      aws_account_id: 037729278610
      stage: "prod"
      app_name: network
